version: '3.1'

services:
    generator:
        build: 
          context: .
        image: aspnetcore/generator:optimized
        ports:
          - "8080:80"
    mail:
        image: mailhog/mailhog
        ports:
          - "8025:8025"
#          - "1025:1025"  Don't need since it's all in the same container